the3DMarket/config/routes.rb
Rails.application.routes.draw do
  
  # Main Controller
  ## Frontpage
  root 'main#index'
  ## About
  #get 'about' => 'main#about'
  
  # Author Controller
  ## Search
  #get 'a/search/:query' => 'author#search'
  ## Show
  #get 'a/:id' => 'author#show'

  # User Controller
  ## Sign Up
  get 'u/browse' => 'user#browse'
  get 'u/create' => 'user#create'
  post 'u/try_create' => 'user#try_create'
  ## Settings
  get 'u/view' => 'user#index'
  patch 'try_index' => 'user#try_index'
  ## Login
  get 'login' => 'user#login'
  post 'logout' => 'user#logout'
  post 'try_login' => 'user#try_login'
  ## Show current user's library
  get 'u/library' => 'user#library'
  ## Show
  get 'u/:id' => 'user#show', as: :user

  # Design Controller
  ## Upload
  get 'd/create' => 'design#create'
  post 'd/try_create' => 'design#try_create'
  ## Search
  get 'd/search' => 'design#search', as: 'search'
  ## View All
  get 'd/view-all' => 'design#index'
  post 'd/view-all' => 'design#index'
  ## Add A Bookmark
  post 'd/bookmark' => 'design#try_bookmark'
  ## Show
  get 'd/:id' => 'design#show', as: 'design'
  ## About
  get 'about' => 'design#about'
  ## Contact
  get 'contact' => 'design#contact'
  ## Legal
  get 'legal' => 'design#legal'
  
end

the3DMarket/app/models/design.rb
class Design < ActiveRecord::Base
  belongs_to :user
  belongs_to :license
  has_many   :bookmarks
end

the3DMarket/app/controllers/design_controller.rb
require 'fileutils'

class DesignController < ApplicationController
  # Design View page
  def browse
    if params[:id].nil? # Handle 
      redirect_to d_view_all_path
    else
      @design = Design.find(params[:id])
    end
  end
  def show
    if params[:id].nil? # Handle 
      redirect_to d_view_all_path
    else
      @design = Design.find(params[:id])
      if @user.present?
        @bookmarked = Bookmark.find_by_user_id_and_design_id(@user.id,@design.id).present?
      end
    end
  end
  # Design Upload page
  def create
    # Make sure user is logged in first
    if !@user.present?
      cookies[:error] = "You must be logged in to do that"
      redirect_to(login_path) and return
    end
  end
  # Validate and upload the file
  def try_create
    if !@user.present?
      cookies[:error] = "You must be logged in to do that"
      redirect_to(login_path) and return
    end
    
    cur_design = Design.create({
                  title: params[:title],
                  sdesc: params[:sdesc],
                  user_id: @user.id,
                  license_id: 1})
    
    cur_design.filepath = '/designs/' + cur_design.id.to_s + '.stl'
    cur_design.imagefilepath = '/designs/' + cur_design.id.to_s + '.jpg'
    
    # Make folder for user if it doesn't exist
    dir = File.dirname('/designs/')
    unless File.directory?(dir)
      FileUtils.mkdir_p(dir)
    end
    
    stl_saved_file = File.new(Rails.public_path.to_s + cur_design.filepath,"w")
    stl_saved_file.write(params[:stl_file].read.force_encoding("UTF-8"))
    # Fix Permissions
    stl_saved_file.chmod(0666)
    stl_saved_file.close
    img_saved_file = File.open(Rails.public_path.to_s + cur_design.imagefilepath,"wb"){ |f|
                        f.write(params[:image_file].read)
                        f.chmod(0666)
                     }
    cur_design.save
    cookies[:success] = "Files successfully uploaded"
    
    redirect_to d_view_all_path and return
  end
  def upload
    if params[:id].nil? # Handle 
      redirect_to d_create_path
    else
      @design = Design.find(params[:id])
    end
  end
  # Design Search page
  def search
    added = false
    query_string = ""
    conditions = {}
    if params[:title].present?
      conditions[:title] = '%' + params[:title] + '%'
      query_string = "title LIKE :title"
      added = true
    end
    
    if params[:date].present?
      conditions[:created_at] = params[:date]
      query_string += " AND " if added
      query_string += "created_at LIKE :created_at"
    end
    
    @designs = Design.where(query_string, conditions).to_a
    
    if params[:author].present?
      @designs.keep_if do |design|
        (design.user.username =~ Regexp.new(params[:author])).present?
      end
    end
    
    render 'index'
  end
  # Design View All page
  def index
    @page_size = 10
    if params[:offset].present? and params[:offset].to_i > 0
      @current_offset = params[:offset].to_i
      @designs = Design.order('created_at ASC').offset(@current_offset).first(@page_size)
    else
      @designs = Design.first(@page_size)
      @current_offset = 0
    end
  end
  def about
    if params[:id].nil? # Handle 
      redirect_to about_path
    else
      @design = Design.find(params[:id])
    end
  end
  def contact
    if params[:id].nil? # Handle 
      redirect_to contact_path
    else
      @design = Design.find(params[:id])
    end
  end
  def legal
    if params[:id].nil? # Handle 
      redirect_to legal_path
    else
      @design = Design.find(params[:id])
    end
  end
  # Bookmark File
  def try_bookmark
    if !@user.present?
      cookies[:error] = "You must be logged in to do that"
      redirect_to(login_path) and return
    end
    d_id = params[:design_id];
    
    bookmark = Bookmark.new({
                              :user_id => @user.id,
                              :design_id => d_id
                           })
    if Design.find(d_id).nil?
      cookies[:error] = "That design doesn't exist"  
    elsif Bookmark.find_by_user_id_and_design_id(@user.id,d_id).nil?
      bookmark.save
      cookies[:success] = "Files successfully uploaded"  
      redirect_to design_path(d_id) and return
    end
    redirect_to d_view_all_path
  end
end

the3DMarket/app/views/design/create.html.haml
.container
  .col-md-4.col-md-push-4
    %h2
      Create design
    = form_tag '/d/try_create', { :multipart => true } do
      .form-group
        %input.form-control{:type => "text", :name => "title", :placeholder => "Design title"}
      .form-group
        %textarea.form-control{:name => "sdesc", :placeholder => "Short description of your design"}
      .form-group
        %label
          STL file
        = file_field_tag 'stl_file'
      .form-group
        %label
          Image file
        = file_field_tag 'image_file'
      .form-group
        = submit_tag "Upload", :class => ["form-control", "btn", "btn-default"]

the3DMarket/app/views/design/index.html.haml
.container
  %h1
    View All Designs
  .search_container
    = form_tag(search_path, method: "get", class: "search_form") do
      %h2
        Search
      .form-group
        %input.form-control{:type => "text", :name => "title", :placeholder => "Design Name"}
      .form-group
        %input.form-control{:type => "text", :name => "author", :placeholder => "Author Name"}
      %input.form-control.btn.btn-primary{:type => "submit", :value => "Search"}
      %input.form-control.btn{:type => "reset", :value => "Clear"}
  - @designs.in_groups_of(4, false).each_with_index do |group|
    .row
      - group.each do |item|
        .col-md-3
          .thumbnail
            %a{:href => design_path(item.id)}
              %img{:src => item.imagefilepath}
            .caption
              %h2
                %a{:href => design_path(item.id)}
                  = item.title
              %p
                = item.sdesc
              %a.btn.btn-primary.btn-sm{:href => design_path(item.id)}
                View details 
  .pagination-links.row
    .col-md-2
      - if @current_offset.present? && @current_offset > 0
        = form_tag(d_view_all_path) do
          = hidden_field_tag 'offset', @current_offset >= @page_size ? @current_offset - @page_size : 0
          %button.form-control.btn.btn-info.pagination-previous{:type => "submit"}
            Previous
    .col-md-2.col-md-push-8
      - if @current_offset.present? && @designs.size >= @page_size
        = form_tag(d_view_all_path) do
          = hidden_field_tag 'offset', @current_offset + @page_size
          %button.form-control.btn.btn-info.pagination-next{:type => "submit"}
            Next
  

the3DMarket/app/views/design/show.html.haml
.container
  %h2
    = @design.title
  .row
    .col-md-6.col-md-push-3
      .design-image.stl-scene{:file_path => @design.filepath}
  .row
    %p
      = @design.sdesc
  .row
    .col-md-4.col-md-push-2
      .form-group
        %select.form-control.controls
          %option{:value => "1"} Controls
          %option{:value => "2"} Controls2
          %option{:value => "3"} Controls3
      .form-group.print
        %input.form-control{:type => "button", :value => "Print"}
    .col-md-4.col-md-push-2
      .form-group
        %select.form-control.settings
          %option{:value => "1"} Settings
          %option{:value => "2"} Settings2
          %option{:value => "3"} Settings3
        -# Download path is @design.filepath
      .form-group
        %form{:method => "get", :action => @design.filepath}
          %button.form-control.btn.btn-primary{:type => "submit"}
            Download
      .form-group
        %button.form-control.btn.btn-default
          License
      .form-group
        - if @bookmarked
          %button.form-control.btn.btn-default.bookmark-design{disabled: "disabled"}
            Purchased
        - else
          %button.form-control.btn.btn-default.bookmark-design
            Purchase 
:javascript
  $.ajaxSetup({
    headers: {
      'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
    }
  });
  $(document).ready(function(){
    if (!Detector.webgl) Detector.addGetWebGLMessage();
    var container, stats;
    var camera, cameraTarget, scene, renderer;
    init();
    animate();
    bind_bookmark_button();
  });
  function bind_bookmark_button () {
    $('button.bookmark-design').click(function(){
      $.ajax({
        type: 'POST',
        url: '#{d_bookmark_path}',
        data: { design_id: '#{@design.id}'}
      })
      .done(function() {
        $('button.bookmark-design').html('Purchased');
        $('button.bookmark-design').prop('disabled',true);
      });
    });
  }

the3DMarket/app/views/design/userpage.html.haml
.container
  .headerContainer
    .header
      %h1 3DEx
      %ul
        %li
          %a{:href => ""} Browse
        %li
          %a{:href => ""} Create
        %li
          %a{:href => ""} Upload
      %span.signin
        %a{:href => ""} Join
        \/
        %a{:href => ""} Sign in
      %span.search
        %button search
        %input{:type => "text"}/
  .content2
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design1
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design2
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design3
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design4
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design5
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design1
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design2
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design3
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design4
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design5
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design1
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design2
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design3
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design4
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design5
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design1
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design2
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design3
    .design
      .picture
        %img{:src => "imgs/2.jpg"}/
      .name
        %h4
          %a{:href => ""} Design4
  .content1
    %h2 User
    %img{:src => "imgs/1.jpg"}/
    .print
      %ul
        %input{:type => "button", :value => "Info"}/
        %select.settings
          %option{:value => "1"} Settings
          = succeed "Settings3" do
            %option{:value => "2"} Settings2
        %input{:type => "button", :value => "Licenses"}/
  .footer
    %img{:src => "imgs/2.jpg"}/
    .clear
    %h3 3DEx
    %ul
      %li
        %a.sectionTitle{:href => ""} About us
      %li
        %a{:href => ""} Blah Blah Blah
      %li
        %a{:href => ""} Blah Blah
    %ul
      %li
        %a.sectionTitle{:href => ""} Contact us
      %li
        %a{:href => ""} Blah Blah Blah
      %li
        %a{:href => ""} Blah Blah
    %ul
      %li
        %a.sectionTitle{:href => ""} Stuff
      %li
        %a{:href => ""} Blah Blah Blah
      %li
        %a{:href => ""} Blah Blah